name: "Dhillon Lab"
description: "This is the official web page for the Jaapna Dhillon Lab at Univeristy of Missouri-Columbia."

url: "https://djaapna.github.io"

paginate: 5
plugins: [jekyll-paginate]
paginate_path: "news/page:num"

permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true

exclude:
        - .sass-cache/
        - .jekyll-cache/
        - gemfiles/
        - Gemfile
        - Gemfile.lock
        - node_modules/
        - vendor/bundle/
        - vendor/cache/
        - vendor/gems/
        - vendor/ruby/

collections:
        members:
                output: true
        publications:
                output: true

theme: jekyll-theme-architect